### ISSUE TITLE
Missing server.pem with default install

### ISSUE THREAD

**Issue by flesueur** [D4-project/d4-core#7]
Hi,

Following the documentation, the server.pem is missing at the end (and sensors cannot connect to core). I could create it successfully with the scripts located in the gen_cert subdirectory.

Cheers,
Francois

**Comment by Terrtia** [comment]
Hi @flesueur ,

Thank for the report !

I added a new [Readme](https://github.com/D4-project/d4-core/blob/master/server/README.md) with an updated documentation.

cheers,

**Comment by flesueur** [comment]
:+1:
